#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🔍 Checking for build errors before commit..."
npm run build
if [ $? -ne 0 ]; then
  echo "❌ Build failed. Commit aborted."
  exit 1
fi

echo "🔍 Running lint-staged before commit..."
npm run lint-staged
